image: Visual Studio 2022

configuration:
  - Release

clone_folder: c:\projects\miasm

environment:
  matrix:
    - PYTHON: "C:\\Python312-x64"
      PYTHON_VERSION: "3.12.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
  - cmd: cd c:\projects\miasm
  - cmd: "python.exe -m pip install -r requirements.txt"
  - cmd: "python.exe -m pip install -r optional_requirements.txt"

build_script:
  - "%PYTHON%\\python.exe setup.py build"
  - "%PYTHON%\\python.exe setup.py install"

test_script:
  - cmd: cd c:\projects\miasm\test
  - "%PYTHON%\\python.exe -W error test_all.py -t gcc"

after_test:
  - cmd: chdir
  - cmd: if "%platform%"=="Win32" 7z a -t7z ..\miasm.x86.release.7z c:\projects\miasm\build\*lib*
  - cmd: if "%platform%"=="X64" 7z a -t7z ..\miasm.x64.release.7z c:\projects\miasm\build\*lib*

artifacts:
  - path: miasm.*.7z
